<a href="https://colab.research.google.com/github/GrowingUnderTheTree/Route-to-machine-learning/blob/main/ArrayShape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np
import pandas as pd

In [3]:
a = np.array([[1,2,3,4,5],[3,4,1,7,9]])

In [4]:
x=a.shape

In [5]:
print(x)

(2, 5)


In [7]:
b = np.array([1,6,5,7,9],ndmin=5)
print(b.shape)

(1, 1, 1, 1, 5)


In [14]:
c = np.array([2,4,6,9,7,8,11,33,19,5,1,3])
nc = c.reshape(2,3,2)
print(nc)

[[[ 2  4]
  [ 6  9]
  [ 7  8]]

 [[11 33]
  [19  5]
  [ 1  3]]]


Array iterating

In [15]:
for x in b:
  print(x)

[[[[1 6 5 7 9]]]]


2D array interating

In [16]:
for i in a:
  for j in i:
    print(j)

1
2
3
4
5
3
4
1
7
9


In [17]:
t = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for k in t:
  for l in k:
    for m in l:
      print(m)

1
2
3
4
5
6
7
8
9
10
11
12


In [19]:
df = pd.read_csv("california_housing_train.csv")

In [20]:
n = np.array(df['housing_median_age'])

In [21]:
print(n)

[15. 19. 17. ... 17. 19. 52.]


In [22]:
for idx, x in np.ndenumerate(n):
  print(idx, x)

Streaming output truncated to the last 5000 lines.
(12000,) 25.0
(12001,) 18.0
(12002,) 19.0
(12003,) 3.0
(12004,) 28.0
(12005,) 15.0
(12006,) 15.0
(12007,) 31.0
(12008,) 30.0
(12009,) 28.0
(12010,) 33.0
(12011,) 18.0
(12012,) 25.0
(12013,) 22.0
(12014,) 26.0
(12015,) 19.0
(12016,) 38.0
(12017,) 12.0
(12018,) 4.0
(12019,) 20.0
(12020,) 36.0
(12021,) 50.0
(12022,) 52.0
(12023,) 40.0
(12024,) 11.0
(12025,) 16.0
(12026,) 17.0
(12027,) 16.0
(12028,) 28.0
(12029,) 41.0
(12030,) 38.0
(12031,) 21.0
(12032,) 36.0
(12033,) 18.0
(12034,) 17.0
(12035,) 18.0
(12036,) 16.0
(12037,) 17.0
(12038,) 14.0
(12039,) 35.0
(12040,) 25.0
(12041,) 24.0
(12042,) 11.0
(12043,) 23.0
(12044,) 10.0
(12045,) 32.0
(12046,) 21.0
(12047,) 44.0
(12048,) 42.0
(12049,) 42.0
(12050,) 42.0
(12051,) 41.0
(12052,) 33.0
(12053,) 34.0
(12054,) 36.0
(12055,) 35.0
(12056,) 23.0
(12057,) 38.0
(12058,) 21.0
(12059,) 35.0
(12060,) 29.0
(12061,) 18.0
(12062,) 37.0
(12063,) 36.0
(12064,) 32.0
(12065,) 21.0
(12066,) 13.0
(12067,) 11.0